# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-25 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180925_0939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseorg',
            name='teacher_tell',
        ),
        migrations.RemoveField(
            model_name='courseorg',
            name='youneed_know',
        ),
    ]
