# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-26 16:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180925_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.CharField(default=0, max_length=3, verbose_name='年龄'),
        ),
    ]
