# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2018-09-15 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180913_1635'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EmainVerifyRecord',
            new_name='EmailVerifyRecord',
        ),
    ]
